services:
  # 1. Base de Datos Global (PostgreSQL)
  postgres-db:
    image: postgres:15-alpine
    container_name: tienda-postgres
    restart: always
    environment:
      POSTGRES_USER: postgresadmin
      POSTGRES_PASSWORD: postgresadmin123
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tienda-network

  # 2. Zipkin (Para rastrear peticiones entre microservicios)
  zipkin:
    image: openzipkin/zipkin
    container_name: tienda-zipkin
    ports:
      - "9411:9411"
    networks:
      - tienda-network

  # 3. pgAdmin (Para ver la BD visualmente en el navegador)
  pgadmin:
    image: dpage/pgadmin4
    container_name: tienda-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-db
    networks:
      - tienda-network

networks:
  tienda-network:
    driver: bridge